# Generated by Django 2.2 on 2019-04-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('Nr', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='analyzedFeedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('bw', models.CharField(max_length=4)),
                ('related', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='democratic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dueDate', models.DateField()),
                ('filePath', models.CharField(max_length=255)),
                ('fid', models.IntegerField()),
                ('pvotes', models.IntegerField()),
                ('nvotes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('fid', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('bw', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.CharField(max_length=255)),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('right', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('related', models.TextField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
