# Generated by Django 2.2 on 2019-04-13 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedfeedbacks',
            name='DateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
