# Generated by Django 2.2 on 2019-04-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0002_analyzedfeedbacks_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='imagePath',
            field=models.ImageField(upload_to=''),
        ),
    ]
