# Generated by Django 2.2 on 2019-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0003_auto_20190414_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='democratic',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='democratic',
            name='filePath',
            field=models.FileField(upload_to='media/democratic/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='imagePath',
            field=models.ImageField(upload_to='media/game/'),
        ),
    ]
