# Generated by Django 2.2 on 2019-04-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0004_auto_20190414_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='fid',
        ),
    ]
