# Generated by Django 2.2 on 2019-04-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0006_auto_20190414_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='democratic',
            name='nvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='democratic',
            name='pvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
