# Generated by Django 2.2 on 2019-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0007_auto_20190414_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='democratic',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='democratic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='democratic',
            name='filePath',
            field=models.FileField(blank=True, null=True, upload_to='media/democratic/'),
        ),
        migrations.AlterField(
            model_name='democratic',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
