# Generated by Django 2.2 on 2019-04-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0008_auto_20190414_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedfeedbacks',
            name='status',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='status',
        ),
    ]
