# Generated by Django 2.2 on 2019-04-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0009_auto_20190414_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedfeedbacks',
            name='related',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='related',
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
