# Generated by Django 2.2 on 2019-04-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0010_auto_20190415_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.IntegerField()),
                ('follower', models.IntegerField()),
            ],
        ),
    ]
