# Generated by Django 2.2 on 2019-04-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0012_analyzedfeedbacks_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='related',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
