# Generated by Django 2.2 on 2019-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0013_wish_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='related',
            name='followed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='related',
            name='follower',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
