# Generated by Django 2.2 on 2019-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0016_auto_20190416_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='democratic',
            name='filePath',
            field=models.FileField(blank=True, null=True, upload_to='democratic/'),
        ),
        migrations.AlterField(
            model_name='democratic',
            name='nvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='democratic',
            name='pvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='imagePath',
            field=models.ImageField(upload_to='game/'),
        ),
    ]
